export const ERROR_CODES = [
  "ERR_INVALID_JSON",
  "ERR_VALIDATION",
  "ERR_RATE_LIMITED",
  "ERR_ROUTE_NOT_FOUND",
  "ERR_INTERNAL",

  "ERR_FIELD_REQUIRED",
  "ERR_FIELD_TOO_LONG",
  "ERR_AMOUNT_REQUIRED",
  "ERR_AMOUNT_TOO_SMALL",
  "ERR_AMOUNT_TOO_LARGE",
  "ERR_AMOUNT_TOO_PRECISE",

  "ERR_CHECKOUT_CHOICE_REQUIRED",
  "ERR_SOURCE_REQUIRED",
  "ERR_SOURCE_LENGTH",
  "ERR_SOURCE_CHARSET",
  "ERR_CUSTOM_AMOUNT_DISABLED",
  "ERR_AMOUNT_OUT_OF_RANGE",
  "ERR_ORDER_RATE_LIMITED",
  "ERR_ORDER_CREATE_FAILED",
  "ERR_PAYMENT_UNAVAILABLE",
  "ERR_ORDER_NO_INVALID",
  "ERR_ORDER_NOT_FOUND",
  "ERR_NOTIFY_REJECTED",
  "ERR_NOTIFY_SAVE_FAILED",

  "ERR_PRODUCT_NOT_FOUND",
  "ERR_PRODUCT_DISABLED",
  "ERR_SORT_ORDER_INVALID",

  "ERR_RANGE_INVERTED",
  "ERR_PRESETS_TOO_MANY",
  "ERR_PRESETS_INVALID",
  "ERR_PRESETS_OUT_OF_RANGE",
  "ERR_REDIRECT_INVALID",

  "ERR_ICON_INVALID",
  "ERR_ICON_TYPE",
  "ERR_ICON_TOO_LARGE",
  "ERR_ICON_URL",
  "ERR_ICON_TEXT_TOO_LONG",
  "ERR_ICON_NOT_SET",

  "ERR_ADMIN_PASSWORD_UNSET",
  "ERR_TURNSTILE_UNSET",
  "ERR_TURNSTILE_FAILED",
  "ERR_WRONG_PASSWORD",
  "ERR_UNAUTHENTICATED",

  "ERR_ALIPAY_KEY",
  "ERR_ALIPAY_UNREACHABLE",
  "ERR_ALIPAY_HTTP",
  "ERR_ALIPAY_NODE_MISSING",
  "ERR_ALIPAY_NODE_NOT_OBJECT",
  "ERR_ALIPAY_NODE_INCOMPLETE",
  "ERR_ALIPAY_SIGN_MISSING",
  "ERR_ALIPAY_REJECTED",
  "ERR_ALIPAY_BAD_SIGNATURE",
  "ERR_ALIPAY_NO_QR",
  "ERR_ROW_MISSING",
  "ERR_PASSWORD_LENGTH",
] as const;

export const CLIENT_ERROR_CODES = ["ERR_NETWORK", "ERR_UNKNOWN"] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export type ClientErrorCode = (typeof CLIENT_ERROR_CODES)[number];

export type AnyErrorCode = ErrorCode | ClientErrorCode;

export type Params = Record<string, string | number>;

export type Issue = { code: ErrorCode; params?: Params };

export type ApiErrorBody = {
  code: ErrorCode;
  params?: Params;
  fields?: Record<string, Issue[]>;
  cause?: ErrorCode;
  request_id?: string;
};
